[package]
name = "project-template"
version = "1.0.0"
edition = "2021"
exclude = ["template"]

[dependencies]
chrobry-core = "1.0"
clap = { version = "4.4", features = ["derive"] }
fs_extra = "1.3"
zip-extract = "0.1"
